# Generated by Django 4.0.6 on 2022-07-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicletas',
            name='rodado',
            field=models.IntegerField(max_length=30),
        ),
    ]
