# Generated by Django 4.0.6 on 2022-07-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicletas',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bicicletas',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='indumentaria',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repuestos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
